//////////
// CORE //
//////////
export const RESET_STATE         = 'RESET_STATE'
export const PROCESS_API_SUCCESS = 'PROCESS_API_SUCCESS'
export const PROCESS_API_FAILURE = 'PROCESS_API_FAILURE'

//////////
// AUTH //
//////////
export const CHECK_BROWSER_TYPE                 = 'CHECK_BROWSER_TYPE'
export const CHECK_RESET_EMAIL_VERIFY_STATUS    = 'CHECK_RESET_EMAIL_VERIFY_STATUS'
export const CHECK_RESET_EMAIL_CONFIRM_STATUS   = 'CHECK_RESET_EMAIL_CONFIRM_STATUS'
export const CHECK_PASSWORDLESS_CONFIRM_STATUS  = 'CHECK_PASSWORDLESS_CONFIRM_STATUS'
export const GET_RESET_EMAIL_ACTION_CODE_STATUS = 'GET_RESET_EMAIL_ACTION_CODE_STATUS'


///////////
// LOGIN //
///////////
export const GET_EMAIL_INPUT_INFO = 'GET_EMAIL_INPUT_INFO'